# Generated by Django 3.0.8 on 2020-07-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='submitcontact',
            new_name='Contact',
        ),
    ]
